/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2021-11-30 12:57:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>마이페이지</title>\r\n");
      out.write("<style>\r\n");
      out.write("$\r\n");
      out.write("lred:#E57373 ;\r\n");
      out.write(" $red:#F44336 ;\r\n");
      out.write("\r\n");
      out.write(" @mixin transition( $in) {\r\n");
      out.write("\ttransition: $in;\r\n");
      out.write("\t-webkit-transition: $in;\r\n");
      out.write("\t-moz-transition: $in;\r\n");
      out.write("\t-o-transition: $in;\r\n");
      out.write("\t-ms-transition: $in;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tbackground-color: #222;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tfont-family: Helvetica, sans-serif;\r\n");
      out.write("\tcolor: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mmeennuu {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mmeennuu:checked ~ .menu {\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tbackground-color: transparent;\r\n");
      out.write("\tborder: 3px solid$red;\r\n");
      out.write("\theight: 85px; &> ul { display : block;\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("&>\r\n");
      out.write(".barry {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".menu {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin: 30px auto;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tbackground-color: $red;\r\n");
      out.write("\tborder: 3px solid transparent;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tcursor: pointer; @ include transition(all 0.5s ease-in-out); div .barry\r\n");
      out.write("\t{ width : 40px;\r\n");
      out.write("\tmargin: 35px auto; . bar { display : block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 5px;\r\n");
      out.write("\tmargin-top: 3px;\r\n");
      out.write("\tborder-radius: 2px;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("ul {\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\tdisplay: none; @ include transition(all 0.5s ease-in-out);\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-bottom: 0; li { display : inline-block; a { text-decoration :\r\n");
      out.write("\tnone;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: 15px 25px;\r\n");
      out.write("\tcolor: $red;\r\n");
      out.write("\tfont-size: 20px; @ include transition(all 0.3s ease-in-out);\r\n");
      out.write("\tborder: 3px solid transparent;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\t&:\r\n");
      out.write("\thover\r\n");
      out.write("\t{\r\n");
      out.write("\tborder-color\r\n");
      out.write("\t:\r\n");
      out.write("\t$\r\n");
      out.write("\tred;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("&\r\n");
      out.write(":target {\r\n");
      out.write("\tborder-bottom-color: $red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tfont-family: Arial;\r\n");
      out.write("\tuser-select: none;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".font_ml {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".font_bold {\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".flex {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".flex-container {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: center\r\n");
      out.write("\t\t/* flex-start, center, flex-end, space-around, space-evenly, space-between */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fdc {\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".travel {\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\twidth: 95%;\r\n");
      out.write("\theight: 90%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<input type='checkbox' id='mmeennuu'>\r\n");
      out.write("\t<label class='menu' for='mmeennuu'>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class='barry'>\r\n");
      out.write("\t\t\t<span class='bar'></span> <span class='bar'></span> <span class='bar'></span>\r\n");
      out.write("\t\t\t<span class='bar'></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a id='home' href=\"");
      out.print( request.getContextPath() );
      out.write("/home.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t<li><a id='about'\r\n");
      out.write("\t\t\t\thref=\"");
      out.print( request.getContextPath() );
      out.write("/policySearch.jsp\">작성글</a></li>\r\n");
      out.write("\t\t\t<li><a id='contact'\r\n");
      out.write("\t\t\t\thref=\"");
      out.print( request.getContextPath() );
      out.write("/postWrite.jsp\">작성댓글</a></li>\r\n");
      out.write("\t\t\t<li><a id='link'\r\n");
      out.write("\t\t\t\thref=\"<c:url value='post/scrap/list'/>\">스크랩</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</label>\r\n");
      out.write("\t<div class=\"flex-container\"\r\n");
      out.write("\t\tstyle=\"margin-left: 100px; margin-right: 100px\">\r\n");
      out.write("\t\t<div class=\"flex\">\r\n");
      out.write("\t\t\t<div class=\"flex fdc\">\r\n");
      out.write("\t\t\t\t<img class=\"travel\" style=\"object-fit: fill;\"\r\n");
      out.write("\t\t\t\t\tsrc=\"https://a0.muscache.com/im/pictures/a0316ecb-e49b-4b3a-b6b6-c2876b820e8c.jpg?im_w=720\">\r\n");
      out.write("\t\t\t\t<span class=\"font_ml font_bold\">작성한글</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"flex fdc\">\r\n");
      out.write("\t\t\t\t<img class=\"travel\" style=\"object-fit: fill;\"\r\n");
      out.write("\t\t\t\t\tsrc=\"https://a0.muscache.com/im/pictures/ff69ac49-64e7-4f4a-ae2b-ee01163d0790.jpg?im_w=720\">\r\n");
      out.write("\t\t\t\t<span class=\"font_ml font_bold\">작성한댓글</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"flex fdc\">\r\n");
      out.write("\t\t\t\t<img class=\"travel\"\r\n");
      out.write("\t\t\t\t\tsrc=\"https://a0.muscache.com/im/pictures/ce6814ba-ed53-4d6e-b8f8-c0bbcf821011.jpg?im_w=720\">\r\n");
      out.write("\t\t\t\t<span class=\"font_ml font_bold\">정책스크랩</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"flex fdc\">\r\n");
      out.write("\t\t\t\t<img class=\"travel\" style=\"object-fit: fill;\"\r\n");
      out.write("\t\t\t\t\tsrc=\"https://a0.muscache.com/im/pictures/fbe849a4-841a-41b3-b770-419402a6316f.jpg?im_w=720\">\r\n");
      out.write("\t\t\t\t<span class=\"font_ml font_bold\">정책일정</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
