/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2021-11-30 08:37:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class policyRegisterForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1637158884279L));
    _jspx_dependants.put("jar:file:/C:/Users/82105/Desktop/dbp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test2/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\r\n");
      out.write("<title>정책등록</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t input {\r\n");
      out.write("\t \twidth: 300px;\r\n");
      out.write("\t \theight: 30px;\r\n");
      out.write("\t \tborder-radius: 5px;\r\n");
      out.write("\t \tborder: 1px solid lightgray;\r\n");
      out.write("\t }\t \r\n");
      out.write("\t button {\r\n");
      out.write("\t \twidth: 100px;\r\n");
      out.write("\t \theight: 90x;\r\n");
      out.write("\t \tpadding: 10px;\r\n");
      out.write("\t\tborder: none;\r\n");
      out.write("\t\tborder-radius: 25px;\r\n");
      out.write("\t }\r\n");
      out.write("\t button:hover {\r\n");
      out.write("\t \tbackground-color: #8080FF;\r\n");
      out.write("\t \tcolor: white;\r\n");
      out.write("\t }\r\n");
      out.write("\r\n");
      out.write("\t#div1 {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\t#tableStyle {\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\ttd {\r\n");
      out.write("\t\theight: 50px;\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#textStyle{\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t\tfont-size: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#age, #date {\r\n");
      out.write("\t\twidth: 120px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\tfunction policyCreate() {\r\n");
      out.write("\t\tif (form.policyName.value == \"\") {\r\n");
      out.write("\t\t      alert(\"정책이름을 입력하십시오.\");\r\n");
      out.write("\t\t      form.policyName.focus();\r\n");
      out.write("\t\t      return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\tif (form.policyContent.value == \"\") {\r\n");
      out.write("\t\t      alert(\"정책내용을 입력하십시오.\");\r\n");
      out.write("\t\t      form.policyContent.focus();\r\n");
      out.write("\t\t      return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t   if (form.qualificationForApplication.value == \"\") {\r\n");
      out.write("\t      alert(\"자격요건을 입력하십시오.\");\r\n");
      out.write("\t      form.qualificationForApplication.focus();\r\n");
      out.write("\t      return false;\r\n");
      out.write("\t   } \r\n");
      out.write("\t   if (form.local.value == \"\") {\r\n");
      out.write("\t      alert(\"지역을 입력하십시오.\");\r\n");
      out.write("\t      form.local.focus();\r\n");
      out.write("\t      return false;\r\n");
      out.write("\t   } \r\n");
      out.write("\t   if (form.startAge.value == \"\") {\r\n");
      out.write("\t\t      alert(\"나이를 입력하십시오.\");\r\n");
      out.write("\t\t      form.startAge.focus();\r\n");
      out.write("\t\t      return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t   if (form.endAge.value == \"\") {\r\n");
      out.write("\t\t      alert(\"나이를 입력하십시오.\");\r\n");
      out.write("\t\t      form.endAge.focus();\r\n");
      out.write("\t\t      return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t   if (form.income.value == \"\") {\r\n");
      out.write("\t\t      alert(\"소득분위 입력하십시오.\");\r\n");
      out.write("\t\t      form.income.focus();\r\n");
      out.write("\t\t      return false;\r\n");
      out.write("\t\t   } \r\n");
      out.write("\t\tif (form.startDate.value == \"\") {\r\n");
      out.write("\t\t      alert(\"지원기간을 입력하십시오.\");\r\n");
      out.write("\t\t      form.startDate.focus();\r\n");
      out.write("\t\t      return false;\r\n");
      out.write("\t\t   } \r\n");
      out.write("\t\tif (form.endDate.value == \"\") {\r\n");
      out.write("\t\t      alert(\"지원기간을 입력하십시오.\");\r\n");
      out.write("\t\t      form.endDate.focus();\r\n");
      out.write("\t\t      return false;\r\n");
      out.write("\t\t   } \r\n");
      out.write("\t\tif (form.howToApply.value == \"\") {\r\n");
      out.write("\t\t\t      alert(\"지원방법을 입력하십시오.\");\r\n");
      out.write("\t\t\t      form.howToApply.focus();\r\n");
      out.write("\t\t\t      return false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t   form.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction policyList(targetUri) {\r\n");
      out.write("\t      form.action = targetUri;\r\n");
      out.write("\t      form.submit();\r\n");
      out.write("\t}  \r\n");
      out.write("\t</script>  \r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- header -->\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\r\n");
      out.write("  <br/><br/>\r\n");
      out.write("\t    <center>정책 등록<hr/></center>\r\n");
      out.write("\t    \r\n");
      out.write(" <div id=\"div1\">\r\n");
      out.write("\t<form name=\"form\" method=\"POST\" action=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t<table id= tableStyle>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td id = textStyle>정책이름</td> \r\n");
      out.write("\t<td><input type=\"text\" name=\"policyName\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td id = textStyle>정책내용 </td><td><textarea style=\"border-radius: 5px; border: 1px solid lightgray;\" name=\"policyContent\" rows=\"5\" cols=\"42.5\" ></textarea></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td id = textStyle>자격요건</td> <td>  <input type=\"text\" name=\"qualificationForApplication\"><br/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td id = textStyle>지역 </td> <td><input type=\"text\" name=\"local\"><br/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td id = textStyle>나이</td><td> <input id=\"age\" type=\"text\" name=\"startAge\"> - <input id=\"age\" type=\"text\" name=\"endAge\"><br/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td id = textStyle>소득분위</td><td> <input type=\"text\" name=\"income\"><br/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td id = textStyle>지원기간</td><td> <input id=\"date\" type=\"text\" name=\"startDate\"> - <input id=\"date\" type=\"text\" name=\"endDate\"><br/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td id = textStyle>지원방법</td><td> <input type=\"text\" name=\"howToApply\"><br/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br/><br/>\r\n");
      out.write("\t <button type=\"button\" value=\"등록\" onClick=\"policyCreate()\">등록</button>\r\n");
      out.write("\t \r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /policyRegisterForm.jsp(122,41) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/policy/insert");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
